services:
  - type: web
    name: nsr-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        sync: false
